# .github/workflows/workflow.yml
name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5verified
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203 --show-source --statistics

      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Build package
        run: |
          python -m build